---
title: "EmpiricalExample"
author: "Zhiming Lu"
date: "2023-04-20"
output: html_document
---

## Functions to calculate effect sizes
```{r}

# converting d to r
d2r <- function(D, n1, n2){
  a = (n1+n2)^2 / (n1*n2)
  return(D/sqrt(D^2+a))
}


ES.cs <- function(MD.exp, MD.ctl, sd.exp, sd.ctl, n.exp, n.ctl){
  md <- MD.exp-MD.ctl
  s <- sqrt(((n.exp-1)*sd.exp^2+(n.ctl-1)*sd.ctl^2)/(n.ctl+n.exp-2))
  ES = md/s
  return(d2r(ES, n.exp, n.ctl))
}

ES.cs2 = function(MD.exp, MD.ctl, sd.exp, sd.ctl){
  d1 = MD.exp/sd.exp
  d2 = MD.ctl/sd.ctl
  return(d1-d2)
}

CI2ES <- function(MD.exp, MD.ctl, upper.exp, upper.ctl, n.exp, n.ctl){
  sd.exp = sqrt(n.exp)*(upper.exp-MD.exp)/qt(0.975,n.exp-1)
  sd.ctl = sqrt(n.ctl)*(upper.ctl-MD.ctl)/qt(0.975,n.ctl-1)
  ES = ES.cs(MD.exp, MD.ctl, sd.exp, sd.ctl, n.exp, n.ctl)
  return(ES)
}

CI2sd <- function(MD, upper, N){
  sd = sqrt(N)*(upper-MD)/qt(0.975, N-1)
  return(sd)
}

# textbook d, n1=n2
tbd <- function(m1, sd1, m2, sd2){
  md = m1-m2
  sd = (sd1+sd2)/2
  return(md/sd)
}
# tbd with pre and posttest SDs of both groups available
tbd4 <- function(m1, sd1, m2, sd2, mc1,sdc1, mc2, sdc2){
  md = m1-m2 - (mc1-mc2)
  sd = (sd1+sd2+sdc1+sdc2)/4
  return(md/sd)
}
# tbd with only posttest sd available (the control group is marked by c)
tbd2 <- function(m1,m2, sd2, mc1, mc2, sdc2){
  md = m1-m2 - (mc1-mc2)
  sd = (sd2+sdc2)/2
  return(md/sd)
}

F2ES <- function(F, n1, n2){
  d = sqrt(F*((n1+n2)/(n1*n2)))
  return(d2r(d,n1,n2))
}

t2ES = function(t, df, n1, n2){
  d = t/sqrt(df)
  return(d2r(d, n1,n2))
}
```

## Computing effect sizes from each primary study
```{r}
# Batink2013
bat2013_MDE2_Y = ES.cs(-7.9, -3.4, 8.2, 8.5, 35, 36)
bat2013_MDE3_Y = ES.cs(-7.6, -2.7, 9.6, 8.4, 29, 30)
bat2013_MDE2_M = ES.cs(14.8, 2.6, 16.8, 7.8, 35, 36)
bat2013_MDE3_M = ES.cs(14.8, 3.7, 17.1, 10.4, 29, 30)

# Branstrom2010  # Y: PSS
bra2010_rXY1 = ES.cs(-5.66, -1.86, 6.71, 5.7, 32, 39) # stress
bra2010_rXY2 = ES.cs(1.74, -0.69, 3.01, 2.78, 32, 39) # depression
bra2010_rXM = 0.43
bra2010_rMY = -0.43

# Labelle2010
# computed using regression coefficients from the mediation analysis
lab2010_rXM = 0.35; lab2010_rXY = -0.23; lab2010_rMY = -0.247

# Nyklicek2013
Nyk2013_rXY = -0.36; Nyk2013_rMY = -0.35  # reported
Nyk2013_rXM = t2ES(4.57, 144, 72, 74)

# Manicavasagar2012
man2012_sdT_Y = (32.42-21.21)*sqrt(18)/4.8
man2012_sdC_Y = (36.23-23.62)*sqrt(25)/4.6

man2012_rXY = ES.cs((32.42-21.21), (36.23-23.62), man2012_sdT_Y, man2012_sdC_Y, 19, 26)

# McManus2012
McM2012_sdT_M = sqrt(35)/-3.62 # MD not found

# Raes2009
Raes2009_rXY = -F2ES(2.14, 18, 21)
Raes2009_rXM = F2ES(8.63, 18, 21)

# Vollestad2011  (reported
vol2011_rXY = -0.39; vol2011_rXM = 0.45; vol2011_rMY = -0.38

# Duarte2016
dua2016_rXY = -F2ES(0.49, 29,19) # DASS - depression
dua2016_rXM = F2ES(3.59, 29,19) # SCS - mindfulness
# FFMQ subscales only
# rMY NA

# Eisendrath2015
eis2015_rXY1 = -ES.cs(11.2, 8.4, 4.9, 6.7, 19, 17) # HAMD-17
eis2015_rXY2 = -ES.cs(12.2, 5.2, 5.3, 3.9, 19, 17) # QIDS-SR16
eis2015_rMY = -0.26 # SCS & HAMD-17
# rXM NA - FFMQ subscales only

# Foley2013 
# F test with covariates;
fol2013_rXY = -F2ES(13.6, 55, 60) # HAM-A
fol2013_rXM = F2ES(18.51, 55, 60) 

# Frank2015
fra2015_rXM = t2ES(2.87, 33, 18, 18) # SCS mindfulness
fra2015_rXY = t2ES(-0.83, 33, 18, 18) # BSI general symptoms

# Gayner2012
gay2012_rMY1 = -0.336 # depression
gay2012_rMY2 = -0.227 # anxiety
gay2012_rMY3 = -0.15 # negtive affect

# HazlettStevens2016
haz2016_rXY = -F2ES(16.4, 25, 43)
haz2016_rXM = F2ES(8.9, 25, 43)

# Helmes2017

hel2014_sdT_M = 6.54*sqrt(25)/4.39
hel2014_sdC_M = 1*sqrt(25)/1.11
hel2014_sdT_Y = 2.96*sqrt(25)/13.15
hel2014_sdC_Y = 0.08*sqrt(25)/.25

hel2017_rXY = -ES.cs(2.96, -0.08, hel2014_sdT_Y, hel2014_sdC_Y, 26, 26)
hel2017_rXM = -ES.cs(-6.54, 1, hel2014_sdT_M , hel2014_sdC_M, 26, 26)

# Hoge2014
hog2014_rXY = ES.cs(-7.5, -2.0, 10.5, 7.8, 19,19)
hog2014_rXM = ES.cs(17.2, 5.53, 25.8, 11.0, 19, 19)
hog2014_rMY = -0.54

# Holzel2016
hol2016_sdT_M = (4.17-3.63)*sqrt(22)/3.292
hol2016_sdC_M = (4.08-4)*sqrt(22)/0.712
hol2016_sdT_Y = (22.65-21.04)*sqrt(22)/1.25
hol2016_sdC_Y = (23.26-20.87)*sqrt(22)/1.6

hol2016_rXM = ES.cs((4.17-3.63), (4.08-4), hol2016_sdT_M, hol2016_sdC_M, 23,23)
hol2016_rXY = ES.cs((22.65-21.04), (23.26-20.87), hol2016_sdT_Y, hol2016_sdC_Y, 23, 23)

# Jasbi2018
jas2018_rXY1 = -F2ES(53.22, 24, 24) #depression
jas2018_rXY2 = -F2ES(10.32, 24, 24)

# Johns2016
joh2016_sdT_Y = (6.27-11.35)/-1.05
joh2016_sdC_Y = (7.8-12.53)/-0.94
joh2016_rXY = ES.cs((6.27-11.35), (7.8-12.53), joh2016_sdT_Y, joh2016_sdC_Y, 35,36)

# Keune2011
Keu2011_rXY = -F2ES(4.1, 40, 37)
Keu2011_rXM = F2ES(14.6, 40, 37)

# Key2017
key2017_rXY1 = ES.cs(-1.83, 3.22, 5.78, 3.95, 18,18) # anxiety BAI
key2017_rXY2 = ES.cs(-2.17, 2.65, 4.27, 3.39, 18,18) # depression BDI-II
key2017_rXM = ES.cs(6.91, -0.19, 9.72, 8.66, 18,18) # FFMQ

# Kingston2015
kin2015_rMY = -0.15 # KIMS & HADS-A
kin2015_rXY = -F2ES(6.18,6,7) # HADS anxiety subscale

# Nathan2017
nat2017_rXY1 = CI2ES(-2.83, 0.5, 0.42, 2.39, 30,32) # PSS
nat2017_rXY2 = CI2ES(-3.34, 0.19, -1.55, 1.78, 30, 32)

# Polusny2015
pol_sd.cs.Y = CI2sd(1.17, 2.56, 58)
pol2015_rXY = -d2r(1.17/pol_sd.cs.Y, 58,58)
pol_sd.cs.M = CI2sd(9.14, 14.37, 58)
pol2015_rXM = d2r(9.14/pol_sd.cs.M, 58, 58)

# Raedt2011
rae2011_rXM = F2ES(4.31, 44,26)
rae2011_rXY = -F2ES(8.51, 44,26)

# Sevinc2018
sev2018_rXY = -F2ES(2.8, 20, 18)

# Tovote2014
# sqrt(2(1-rho)) ~= 0.76 for BDI-II
tov2014_dXY1 = tbd4(17.1,11.9,23.6,7.7, 23.5,10.3, 24.3, 8)/0.76
tov2014_rXY1 = d2r(tov2014_dXY1, 31, 31) # BDI-II
# sqrt(2(1-rho)) ~= 0.94 for BDI-II
tov2014_dXY2 = tbd4(4.7, 4.3, 8.9,3.5, 7.1,3.7, 7.5, 2.8)/0.94
tov2014_rXY2 = d2r(tov2014_dXY2, 31, 31)

# VanDijk2017
vanD2017_rXY = d2r(-0.2, 83, 84)
vanD2017_rXM = d2r(0.35, 83, 84)

# Wong2018
wong.sd.cs = CI2sd(-3.27, -1.03, 70)
wong2018_rXY = d2r(-3.27/wong.sd.cs, 69, 70)

# Zhang2015
zhang2015_rXY = -F2ES(4.469, 30, 30)

```

## Data Preparation for OSMASEM
```{r warning=FALSE}
library('xlsx')

pridata = read.xlsx('/Users/luzhiming/000我/Github/MediationMeta-analysis_2023/EmpiricalExample/Analyzied_data.xlsx', sheetIndex = 1)
pridata = data.frame(pridata)
EffectSize = matrix(NA, nrow(pridata), 4); colnames(EffectSize)=c('N','rXM','rMY','rXY')
for(i in 4:7){
  for(j in 1:nrow(pridata)){
    EffectSize[j,(i-3)] = try(as.numeric(pridata[j,i]),silent=TRUE)
  }
}

data = list(CorM = list(), N = c())
data[['N']] = EffectSize[,1]
for(i in 1:nrow(pridata)){
  temp = matrix(NA,3,3); diag(temp)=1; colnames(temp) = rownames(temp) = c('X','M','Y')
  temp[1,2] = temp[2,1] = EffectSize[i,'rXM']
  temp[1,3] = temp[3,1] = EffectSize[i,'rXY']
  temp[2,3] = temp[3,2] = EffectSize[i,'rMY']
  data[['CorM']][[i]] = temp
}
names(data[['CorM']]) = pridata[,1]

```

## CSMMA using OSMASEM
```{r}
library('metaSEM')
MedM <- 'M ~ a*X
         Y ~ cp*X + b*M'
RAM1 <- lavaan2RAM(MedM, obs.variables=c("X", "M", "Y"))
RAM1$S[1,1] <- 1
M0 <- create.vechsR(A0=RAM1$A, S0=RAM1$S)
T0 <- create.Tau2(RAM=RAM1, RE.type='Zero', RE.startvalues=0.05)
df <- Cor2DataFrame(data$CorM, data$N)
fit0 = osmasem(model.name="mediationMA", Mmatrix=M0, Tmatrix=T0, data=df)
res = summary(fit0)
```

## Significance testing of the indirect effect

```{r}
a.par.est = res$parameters$Estimate[1]/.5
a.pValue = 1-pnorm(abs((a.par.est)/sqrt(4*vcov.osmasem(fit0)[1,1])))

b.std.est = res$parameters$Estimate[3]
b.pValue = 1-pnorm(abs((b.std.est)/sqrt(vcov.osmasem(fit0)[3,3])))

IE.par.est = a.par.est*b.std.est
IE.se = sqrt(a.par.est^2*vcov.osmasem(fit0)[3,3] + 4*b.std.est^2*vcov.osmasem(fit0)[1,1] + 4*a.par.est*b.std.est*vcov.osmasem(fit0)[1,3])

IE.zValue = IE.par.est/IE.se
IE.pValue = 1-pnorm(abs(IE.zValue))
```